# Generated by Django 2.2.6 on 2019-11-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='categoria',
            field=models.CharField(choices=[('rest', 'Restrito'), ('prot', 'Protegido'), ('publ', 'Publico')], max_length=4),
        ),
    ]

